cloudposse/.github

- workflow-templates/auto-readme.yml
Update github output syntax
Following github docs
https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
> Update github output syntax

- README.md.gotmpl
- Do not require `README_INCLUDES` environment variable to be defined
- https://github.com/cloudposse/build-harness/pull/368 removed it since it was badly defined
- https://github.com/cloudposse/build-harness/pull/368
- https://github.com/cloudposse/build-harness/pull/100
> Do not require README_INCLUDES to be defined

- README.md
- README.yaml
- SECURITY.md
* Better explain our position on bug bounties and what it means in the context of being an Open Source company
* We want to be clear that it's out of fairness, that we cannot compensate certain contributions over others, when they are all invaluable to our success.
> Update note about bug bounties to be more clear

- .github/workflows/org-banner.yml
- .github/workflows/repo-banner.yml
- workflow-templates/auto-readme.yml
- workflow-templates/test-github-action.yml
- Update `node16` actions to `node20` versions
- `actions/checkout` -> v4
- `stefanzweifel/git-auto-commit-action` -> v5
- Node16 support is deprecated
- https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/
> Update node16 actions to node20 versions

- .github/mergify.yml
- .github/settings.yml
* Add `migration` label 
* Disable `mergeable` condition as it needs to better communicate why something is not mergable
* It will be used to `label` PRs that perform repo migrations
> Add missing migration label

- .github/mergify.yml
- Do not add triage label to PR after it has been removed due to being approved
- Remove infinite loop
- https://github.com/cloudposse/terraform-aws-cloudfront-s3-cdn/pull/295
> Prevent looping on triage label

- .github/auto-release.yml
* `auto-release.yaml` enable  filter-by-commitish
* To support release branches
> `auto-release.yaml` enable  filter-by-commitish

- .github/workflows/shared-auto-release.yml
> Added outputs

- .github/goreleaser.yml
- .github/workflows/shared-auto-release.yml
- .github/workflows/shared-tf-provider-release.yml
> Added go releaser workflow

- .github/workflows/shared-go-auto-release.yml
* Use self-hosted runners for gorelease
* Solve out of space
* https://github.com/cloudposse/terraform-provider-awsutils/actions/runs/8799247307/job/24148159056
> Use self-hosted runners for gorelease

- .github/workflows/shared-go-auto-release.yml
* Go release use app token
* Support private repos
> Go release use app token

- .github/workflows/shared-github-action.yml
*  Fix default ref for shared github action workflow
* Allow to trigger test workflows 
* https://github.com/cloudposse/github-action-test-action/actions/runs/9133786143/job/25118007992
> [share github action workflow] Fix default ref

- .github/workflows/shared-github-action.yml
* Replace ref input with expression
* Use `github.ref` for push events and `github.pull_request.head.ref`
> [shared github action workflow] Get rid of ref input

- .github/workflows/shared-terraform-module.yml
- Update workflow action references to use `main` branch
- The previously mentioned branch does not exist anymore. It was merged with https://github.com/cloudposse/github-actions-workflows/pull/117
- Example of failing module: https://github.com/cloudposse/terraform-aws-managed-prometheus/actions/runs/9292957421
```console
[Invalid workflow file: .github/workflows/branch.yml#L24](https://github.com/cloudposse/terraform-aws-managed-prometheus/actions/runs/9292957421/workflow)
error parsing called workflow
".github/workflows/branch.yml"
-> "cloudposse/.github/.github/workflows/shared-terraform-module.yml@main" (source branch with sha:a7920175625a9e55449656baafda1bd2a82603ba)
--> "cloudposse/github-actions-workflows/.github/workflows/ci-terraform.yml@shared-workflows"
: failed to fetch …
```
> fix: Point Shared Workflows to `main`

- .github/goreleaser.yml
* Escape archive format
* Fix unmarshal error
> Escape archive format

- .github/workflows/shared-github-action.yml
* Pin renamed generation in shared-github-action.yml
* Fix github actions workflows
> Pin renamed generation in shared-github-action.yml

- .github/workflows/shared-release-branches.yml
* Always create new comments for release
* We do not need to update comments as release usually triggered only once
* DEV-2360 GHA Bot to comment instead of edit an existing comment
> Always create new comments for release

- .github/settings.yml
* Added custom branch tag protection
* Allow release workflows auth for release creation
* DEV-124 Add protected tags with Repository Rulesets on GitHub
> Added custom branch tag protection

- .github/workflows/shared-terraform-chatops.yml
* Restrict `terratest` run only to `OWNER`, `MEMBER`, `COLLOBORATOR`
* Allow `terratest` run only for open PR
* Avoid random users to run `terratest` (because of cost and security reason)
* Do not run tests for closed PRs
* https://docs.github.com/en/graphql/reference/enums#commentauthorassociation
> Restrict role that can run terratest

- .github/workflows/shared-terraform-chatops.yml
* Added debug terratest commenter job
* Find out why some contributors can not run `terrratests`
* https://github.com/cloudposse/terraform-aws-ecs-cluster/actions/runs/10776935127
* https://github.com/cloudposse/terraform-aws-cloudfront-cdn/actions/runs/10775216862
> Debug terratest commenter

- .github/workflows/shared-terraform-chatops.yml
* Support custom property `test-aws-role`
* Support custom property `test-skip-concurrency`
* Allow to set custom AWS role for terratest 
* Allow running terraform / opentofu tests in a row
> Added read custom properties for terratest

- .github/auto-release-hotfix.yml
- .github/auto-release.yml
* Fix release changelog space issue
* Have nice changelog
* https://github.com/cloudposse/terraform-aws-components/pull/1117/files#diff-06572a96a58dc510037d5efa622f9bec8519bc1beab13c9f251e97e657a9d4edR10
> Fix release changelog space issue

- .github/workflows/shared-terraform-module.yml
* Use the GitHub app for code owners validation
* Get rid of PAT for security reasons
* DEV-2144 Create GitHub app for code-owners testing
* https://linear.app/cloudposse/issue/DEV-2144/create-github-app-for-code-owners-testing
> Use github app for codeowners validation

- README.md.gotmpl
* Added explicit default value for `README_INCLUDES` environment variables
* Starting from [gomplate `4.2.0`](https://github.com/hairyhenderson/gomplate/releases/tag/v4.2.0) includes required implicit definition starting with "./" or "/"
* https://sweetops.slack.com/archives/CUJPCP1K6/p1731416487743859
* https://github.com/cloudposse/terraform-aws-alb/actions/runs/11795616491/job/32869718771
* https://github.com/hairyhenderson/gomplate/pull/2255
> Fix readme template

- .github/mergify.yml
* Added mergify rule to close PR to `cloudposse/terraform-aws-components`
* We want to close all new PRs because of the code freeze
* https://github.com/cloudposse/terraform-aws-components/issues/1177
> [mergify] Code freeze rules

- .github/mergify.yml
* Update mergify PR messages for component migration
* Migration is done, so we need to update comments' text
* https://github.com/cloudposse/terraform-aws-components/issues/1177
> Migration completed

- .github/runs-on.yml
- Add sharable runner configuration for self-hosted GitHub Action Runners managed by Runs-On
- Provide a central point of configuration so updates are automatically available to all
- https://runs-on.com/configuration/repo-config/
> Add runner configuration for Runs-On

- .github/runs-on.yml
- Update Runs-On configuration
- Remove `s3-cache` setting from all runners
- Add comments 
- Better reflect Cloud Posse usage
- Magic `s3-cache` breaks artifact up/downloads if not combined with [runs-on/action](https://github.com/runs-on/action), so it should be set per-job, not by default.
- Compare to GitHub hosted runners
- Caution against blindly adopting these definitions in other circumstances
> Updated runs-on confguration

- .github/runs-on.yml
- Limit RunsOn instances to "standard" instance families
- Non-standard instances are subject to service quotas that can be as low as zero by default. We want to be able to launch a lot of instances, and need a high quota, so we should stick to the standard instances that share the same single quota we have already increased.
> [RunsOn] Limit instance families to standard types

- .github/workflows/shared-go-auto-release.yml
* Free space before run go release
* Go release needs more space for terraform providers repos
* https://github.com/cloudposse/terraform-provider-awsutils/actions/runs/13504257115/job/37759763107
> Free space before run go releaser

- .github/workflows/shared-go-auto-release.yml
* Add `--ignore-missing` to apt-get remove command
* Fix space cleanup space command
> Fix free space go releaser

- .github/runs-on.yml
- Move GitHub Action Runners to public subnets
- Save money on NAT and network traffic charges
> Move GHA runners to public subnets

- .github/workflows/shared-go-auto-release.yml
* Go releaser use default parallelism
* Better utilize CPU for runs-on runners
> Go releaser use default parallelism

- .github/workflows/shared-auto-release.yml
- .github/workflows/shared-go-auto-release.yml
* Pin `cloudposse/github-action-auto-release` to  v3.0.0 
* Do not issue new releases if there are any for the current commit
> Do not create empty releases

- .github/workflows/shared-auto-release.yml
* Temporary use cloudposse/github-action-auto-release v2
* cloudposse/github-action-auto-release v3 have bug
> Temporary use cloudposse/github-action-auto-release v2

- .github/workflows/shared-auto-release.yml
* Use cloudposse/github-action-auto-release v3
* Do not issue duplicated releases
> Use cloudposse/github-action-auto-release v3

- .github/workflows/shared-terraform-chatops.yml
* Set chatops Terraform AWS auth token TTL 2 hours
* Solve issue with token expiration when tests runs longer then 1 hour (default)
> [chatops] Terraform AWS auth token ttl 2 hours

- .github/workflows/shared-access-controller.yml
* Allow mergify run terratests
* To improve auto update PRs review process
* DEV-3127: Make sure /terratest commands are automated on rennovate PRs
> Allow mergify run terratests

- .github/workflows/shared-access-controller.yml
I think this is the place to add allowing running `/terratest` chatops in the GitHub PR comments? I was just recently added to the contributors org group and I thought that would be it, but seems like this file is the actual source.
> chore: allow terratest user

- .github/mergify.yml
* Specify bot name for mergify rebase configs
* Mergify use PR author for rebase author, but it is impossible to act as github app bot.
Rebase rule fail for such PRs
* DEV-3292 Investigate Mergify dispatch issue not working
> Fix rebase auto created PRs

- .github/goreleaser.yml
* Go releaser support custom target commitish
* Required for `feature releases`
> Go releaser support custom target commitish

- .github/auto-feature-release.yml
* Feature release prerelease identifier change
* `prerelease identifier` used in version sorting
> Feature release prerelease identifier change

- .github/workflows/shared-terraform-chatops.yml
* Use the Github test app for terratests github auth
* Improve security by having short live token
> Use Github test app for terratests github auth

- .github/workflows/shared-ci-github-action.yml
* Pass SHA to GHA tests workflows
* SHA is usefull in tests scenarious
> Pass SHA to GHA tests workflows

- .github/workflows/shared-release-branches.yml
* Skip pre releases
* Prevent Cloud Posse Release Branch Manager to Respect Prerelease Flag
* https://linear.app/cloudposse/issue/DEV-3436/prevent-cloud-posse-release-branch-manager-to-respect-prerelease-flag
> Skip pre releases

- .github/workflows/shared-ci-terraform.yml
* Pin reviewdog to [v1.22.0](https://github.com/reviewdog/action-suggester/releases/tag/v1.22.0)
* `1.23.0` have regression https://github.com/reviewdog/action-suggester/pull/98
* https://github.com/reviewdog/action-suggester/pull/98
> Pin reviewdog action to version 1.22.0
