cloudposse/.github

- workflow-templates/pre-commit.properties.json
- workflow-templates/pre-commit.yml
#what 
- test pre-commit workflow
> Add pre-commit workflow

- .github/FUNDING.yml
- README.md
> default funding settings

- .github/workflows/auto-format.yml
- workflow-templates/github-composite-action-bleeding-edge.properties.json
- workflow-templates/github-composite-action-bleeding-edge.yml
- workflow-templates/github-composite-action-pull-request.properties.json
- workflow-templates/github-composite-action-pull-request.yml
* Added Github actions starter workflows
* Added Github composite action starter workflows
* PoC using GHA on org level
* https://cloudposse.atlassian.net/browse/CPLIVE-260
> Added GHA composite workflows

- workflow-templates/github-composite-action-main-branch.properties.json
> Update workflow templates

- workflow-templates/github-composite-action-main-branch.properties.json
> Test workflow templates

- workflow-templates/auto-readme.properties.json
- workflow-templates/auto-readme.yml
- workflow-templates/dockerized-app-feature-branch.properties.json
- workflow-templates/dockerized-app-feature-branch.yml
- workflow-templates/dockerized-app-main-branch.properties.json
- workflow-templates/dockerized-app-main-branch.yaml
- workflow-templates/dockerized-app-release.properties.json
- workflow-templates/dockerized-app-release.yaml
- workflow-templates/github-composite-action-feature-branch.properties.json
- workflow-templates/github-composite-action-main-branch.properties.json
* Added `dockerized-app` workflows
* Added `auto-readme` workflows
> Added dockerized app workflows

- workflow-templates/auto-readme.properties.json
- workflow-templates/auto-readme.yml
- workflow-templates/dockerized-app-feature-branch.properties.json
- workflow-templates/dockerized-app-feature-branch.yml
- workflow-templates/dockerized-app-main-branch.properties.json
- workflow-templates/dockerized-app-main-branch.yaml
- workflow-templates/dockerized-app-release.properties.json
- workflow-templates/dockerized-app-release.yaml
- workflow-templates/github-composite-action-feature-branch.properties.json
- workflow-templates/github-composite-action-main-branch.properties.json
- workflow-templates/test-github-action.properties.json
- workflow-templates/test-github-action.yml
* Added `Test GitHub Action` workflow
> Added workflow templates

- workflow-templates/github-composite-action-feature-branch.yml
- workflow-templates/github-composite-action-main-branch.yml
* Fix Github composite action workflow
> Fix Github composite action workflow

- README.md
- README.md.gotmpl
- README.yaml
- profile/README.md
* Use `?style=for-the-badge` rectangular badges 
* Use the new shield for SweetOps hosted via CloudFlare worker
* Add CTAs to org profile
* Refresh our look & feel
* They look more like a CTA
> Use Square Badges

- README.md
- profile/README.md
* Move content into `<details/>` block
* Add CTAs
* It's too long as it is, hiding our repos. 
* Extends #31
> Optimize Profile Page

- renovate.json
*fix offending part in renovatbot config
* closes #11
* prevents renovabot from maintaining versions
> fix: renovate bot complaint #11

- .github/mergify.yml
- .github/settings.yml
- migrate/.gitignore
- migrate/Makefile
- migrate/README.md
- migrate/lib/badges.sh
- migrate/lib/codeowners.sh
- migrate/lib/common.sh
- migrate/lib/dependabot.sh
- migrate/lib/editorconfig.sh
- migrate/lib/github-settings.sh
- migrate/lib/gitignore.sh
- migrate/lib/mergify.sh
- migrate/lib/readme.sh
- migrate/lib/renovate.sh
- migrate/migrations/20240302/README.md
- migrate/migrations/20240302/repos.txt
- migrate/migrations/20240302/script.sh
- migrate/migrations/20240302/test-badges.yaml
- migrate/migrations/20240304/README.md
- migrate/migrations/20240304/repos.txt
- migrate/migrations/20240304/script.sh
- migrate/readme/README.md
- migrate/run.sh
- migrate/yamlfix.toml
- Add `migration/` folder for carrying out github repo migrations
- Add `mergify.yml` and `settings.yml`
* Repo automation @ scale
> Implement migrations and initial versions of settings.yml and mergify.yml

- README.md
- README.md.gotmpl
* Depending on available sections, display specific tips
* Tips can get overwhelming if certain sections are empty
> display templates depending on available sections

- README.md
- README.md.gotmpl
- Pass context to readme template
- Broke recently in #47
> Fix templates in README.md.gotmpl

- .github/mergify.yml
- migrate/Makefile
- migrate/README.md
- Check that PR is not a WIP when commenting
- Use explict `and` everywhere needed in anchors
- Delay 5 minutes since last update before welcoming
- Label stale pull requests
- Close stale pull requests 3 days after last update
- Use active voice
- Rename anchors to be more clear
- Use more anchors to make it easier to understand what everything means
- Some edge cases we encountered
- Make mergify less error prone
> Add more conditions for mergify config

- .github/settings.yml
* Update teams permissions
* Fix Codeownership verification
> Update teams permissions

- .github/workflows/shared-auto-release.yml
* Set `auto-release.yml` as the default config
* Follow existing config names pattern
> Update shared-auto-release config name

- .github/workflows/auto-release.yml
* Use auto relesase shared workflow 
* https://cloudposse.atlassian.net/browse/DEV-1747
> Auto release fix

- .github/workflows/shared-auto-release.yml
* Set `release` environment for  `shared-auto-release` workflow
* Reuse existing environment
> Set `release` environment for  `shared-auto-release` workflow

- .github/workflows/shared-auto-release.yml
- .github/workflows/shared-release-branches.yml
> Added release branches

- .github/goreleaser.yml
* Remove `go mod tidy`
* Fix deep deps check https://github.com/cloudposse/github-authorized-keys/actions/runs/8790527824/job/24124632078
> Fix go releaser hooks

- .github/workflows/shared-go-auto-release.yml
* Fix default go releaser runner
> Fix default go releaser runner

- .github/workflows/shared-go-auto-release.yml
> Go releaser fix GHA token

- .github/workflows/shared-go-auto-release.yml
> Go release permissions fix

- .github/goreleaser.yml
* Support archive format input
* Handle binary artifacts for release
> Support archive format

- .github/workflows/shared-go-auto-release.yml
> Fix description shared-go-auto-release.yml

- .github/workflows/shared-go-auto-release.yml
> Fix go releaser workflow

- migrate/migrations/20240501/README.md
- migrate/migrations/20240501/repos-00
- migrate/migrations/20240501/repos-01
- migrate/migrations/20240501/repos-02
- migrate/migrations/20240501/repos-03
- migrate/migrations/20240501/repos-04
- migrate/migrations/20240501/repos-05
- migrate/migrations/20240501/repos-06
- migrate/migrations/20240501/repos-07
- migrate/migrations/20240501/repos-08
- migrate/migrations/20240501/repos-09
- migrate/migrations/20240501/repos-10
- migrate/migrations/20240501/repos.sh
- migrate/migrations/20240501/script.sh
- migrate/templates/terraform-module/.github/workflows/feature-branch.yml
- migrate/templates/terraform-module/.github/workflows/release-branch.yml
- migrate/templates/terraform-module/.github/workflows/scheduled.yml
* Update terrraform modules GHA workflows
> Add Repo Migration to Update terrraform modules GHA workflows

- .github/workflows/shared-github-action.yml
- .github/workflows/shared-terraform-chatops.yml
- .github/workflows/shared-terraform-module.yml
- .github/workflows/shared-terraform-scheduled.yml
* Consolidate shared workflows
* Reduce reusable workflows nested levels
* DEV-400: Move shared workflows into .github repo with shared- prefix
> Consolidate shared workflows

- README.md
- README.md.gotmpl
- profile/README.md
* Serve banner from canonical URL
* Terraform registry doesn't support relative URLs 💩
> Update README template to use canonical URLs

- .github/workflows/shared-terraform-module.yml
* Fix terraform modules workflow
* Pin the right version
> Fix terraform modules workflow

- .github/workflows/shared-terraform-module.yml
* Make `REPO_ACCESS_TOKEN` secret optional
* Fix forks workflows run
> [shared-terrarform-moduke-workflow] Make secret optional

- .github/workflows/shared-release-branches.yml
* Fix release commenter intend
* To have well formated comments
> Fix release commenter indent

- .github/goreleaser.yml
> Fix fix-goreleaser-config

- .github/workflows/shared-go-auto-release.yml
* Fix goreleaser workflow typo
* Fix goreleaser
> Fix goreleaser workflow typo

- workflow-templates/scorecard.yml
- add scorecard github action
- publish results on openssf website
- able to showcase scores using a badge
- https://securityscorecards.dev/#how-it-works
- example of an existing project https://scorecard.dev/viewer/?uri=github.com/ossf/scorecard-action
- example for tested internal project https://scorecard.dev/viewer/?uri=github.com/cloudposse/terraform-module-test
- main repo https://github.com/ossf/scorecard
- action https://github.com/ossf/scorecard-action
- borrowed from https://github.com/renovatebot/renovate/blob/9b64288861fcebfcce7a4938307dec52c04ec54f/.github/workflows/scorecard.yml#L2
- Tested in https://github.com/cloudposse/terraform-module-test/pull/117
> feat: add scorecard

- .github/settings.yml
* Add `test` environment
* Allow to store secrets for `terratest` 
* DEV-387 Update the atmos release workflows to trigger the workflow dispatch
> Add `terratest` environment

- .github/workflows/shared-terraform-chatops.yml
> Terratest refactoring

- .github/workflows/shared-access-controller.yml
- .github/workflows/shared-terraform-chatops.yml
* Implement `access controller` shared workflow
* Use `access controller` shared workflow to grant users access to run terratest
* Restrict permissions to chatops commands
* Restrict access who can run terratest
> Added terratest user permissions

- .github/mergify.yml
* Disable PR close for terraform-aws-components
* Allow update README
* https://github.com/cloudposse/terraform-aws-components/issues/1177
> Disable PR close for terraform-aws-components

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/config.yml
- .github/ISSUE_TEMPLATE/feature_request.md
- .github/mergify.yml
- CODE_OF_CONDUCT.md
- README.md
- README.md.gotmpl
- README.yaml
- SUPPORT.md
- migrate/lib/readme.py
- migrate/migrations/20240302/test-badges.yaml
- profile/README.md
* Use the registration page at cloudposse.com/slack instead of directly linking to slackin-extended
* Provide more details about the slack community
> Update slack url

- .github/workflows/shared-go-auto-release.yml
* Check free space size
* Fix run out of space
> Check free space size

- .github/auto-pre-release.yml
> Add auto-pre-release config

- .github/auto-pre-release.yml
- .github/auto-release.yml
- .github/workflows/shared-auto-release.yml
> Use config for pre-releases

- .github/workflows/shared-terraform-chatops.yml
> Improve go tests summary

- .github/workflows/shared-terraform-chatops.yml
> Fix terratest workflow

- .github/workflows/shared-ci-github-action.yml
- .github/workflows/shared-github-action.yml
- .github/workflows/shared-readme.yml
* Move `ci-readme` shared workflows from https://github.com/cloudposse-archives/github-actions-workflows/tree/main/.github/workflows
* We use that workflows
> Move shared workflows

- .github/workflows/shared-terraform-module.yml
* Fix terraform module CI
* Fix workflows
> Fix terraform module CI

- README.md.gotmpl
* Rebuild the readme with Atmos
* Build-harness depricated
> Rebuild readme with atmos

- README.md.gotmpl
* Readme template support GHA
* Atmos readme generation support
> Readme template support GHA

- .github/mergify.yml
* Stop closing PRs on conflict
* That's does not follow new policy
* https://sweetops.slack.com/archives/G014YEKDH4K/p1748625979533649
> Stop closing PRs on conflict

- .github/atmos/terraform-module.yaml
- README.md.gotmpl
* Refactor README.md.gotmpl to simplify logic 
* Added `get support`  badge
* Improve adverticity   
* DEV-3280 Add "Get Support" Badge in atmos.yaml config
> Added get support badge

- README.md.gotmpl
* Added module testing description
* Help developers to run tests on local 
* DEV-3260 Update README.md.gompl with instructions for running tests
> Added module testing description

- .github/auto-feature-release.yml
* Added `feature release` config for draft release
* To be able to cut `feature` release from PRs
> Added `feature release` config for draft releaser

- .github/auto-feature-release.yml
* Feature release no changelog
* Changelog would be too long
> Feature release no changelog

- .github/auto-feature-release.yml
> Fix feature release config

- .github/auto-feature-release.yml
* Feature release prerelease identifier
* Test feature release
> Feature release prerelease identifier

- .github/auto-feature-release.yml
* Rename feature release suffix to `test`
* `test` suffix is better then `xyz`
> Rename feature release suffix to `test`

- README.md.gotmpl
> Fix README.md.gotmpl

- .github/auto-feature-release.yml
- .github/workflows/shared-auto-release.yml
* Feature releases added release description
* Allow to get more context about the release
> Feature releases added release description

- .github/auto-feature-release.yml
- .github/settings.yml
* Fix the releases template
* Better description
> Fix releases template

- .github/workflows/shared-auto-release.yml
> Fix auto release

- .github/workflows/shared-access-controller.yml
* Added access rules to create feature releases
* Improve feature releases workflow
> Added access rules to create feature releases

- .github/workflows/shared-auto-release.yml
* Fix feature release PR comment
> Fix feature release PR comment

- .github/workflows/shared-auto-release.yml
> Fix release drafter comment

- .github/workflows/shared-auto-release.yml
* Fix feature release comments
> Fix feature release comments

- .github/workflows/shared-auto-release.yml
> Fix workflows typo

- .github/workflows/shared-auto-release.yml
> Use github default token

- .github/workflows/shared-auto-release.yml
* Disable comment on auto release
> Disable comment on auto release

- .github/goreleaser.yml
- .github/workflows/shared-go-auto-release.yml
* Go releaser config support draft mode
> Go releaser config support draft mode

- .github/goreleaser.yml
- .github/workflows/shared-go-auto-release.yml
> Rollback Go releaser config

- README.md.gotmpl
* Fix closing tag for details section in README template
* Fix docs generation
> Fix closing tag for details section in README template

- .github/atmos/default.yaml
- .github/atmos/github-action.yaml
- .github/atmos/terraform-module.yaml
- .github/workflows/shared-readme.yml
* Add command to generate README in Atmos config
* Use https://github.com/cloudposse-github-actions/readme/releases/tag/v2.0.0
> Add command to generate README in Atmos config

- .github/workflows/shared-readme.yml
* Update readme action to use version 2
> Update readme action to use version 2

- .github/workflows/shared-atmos-readme.yml
* Upgrade readme action from v1 to v2
* Fix readme generation with atmos
> Upgrade readme action from v1 to v2

- README.md.gotmpl
* Fix formatting and update Terraform usage tips
> Fix formatting and update Terraform usage tips

- README.md.gotmpl
* Fix variable reference for Terraform condition
> Fix variable reference for Terraform condition
